MEDIA_TAGS = [
    "Manga",
    "Anime",
    "Light Novel",
    "Manhwa",
    "Manhua",
    "NSFW",
    "Onscreen",
    "Webtoon",
    "Hair Salon"
]

STYLE_TAGS = [
    "Long",
    "Bob",
    "Pixie",
    "Bald",
    "Dye",
    "Braid",
    "Twintail",
    "Ponytail",
    "Himecut",
    "Wolfcut",
    "Curly Hair",
    "Short Hair",
    "Straight Bangs",
    "Short Bangs",
    "Alternative",
    "Other"
    "Straight Bangs",
    "Short Bangs",
    "Blonde",
    "Redhead",
    "Black Hair",
    "White Hair" , 
    "Brown Hair",
    "Pink Hair",
    "Purple Hair",
    "Blue Hair",
    "Very Long Hair",
    "Undercut",
    "Green Hair",
    "Drill Hair",
    "Orange Hair"  
]